### ISSUE TITLE
definite bug line 436....

### ISSUE THREAD

**Issue by proseLA** [torvista/zen-cart_product_listing_sorter#1]
you have an extra period on line 436.

`      $order_str .= " order by p.products_sort_order, pd.products_name";`

should be:

`      $order_str = " order by p.products_sort_order, pd.products_name";`

if you look at line 430, you will see no period.

best.

**Comment by torvista** [comment]
Blimey, that was fast!
Although I agree, I cannot trigger the fault reported in the forum, before correcting this.
https://www.zen-cart.com/showthread.php?205606-Product-Listing-Sorter-Drop-Down-Support-Thread&p=1348270#post1348270

**Comment by torvista** [comment]
This is/was a bug in core code, fixed in 156. Actually both sql should have the dot.
The problem the op has are probably due to the 2.0 version code....I made modifications that I forgot to upload.

**Comment by proseLA** [comment]
torvista,
i will make a few comments and then shut up on this thing.

- good for you putting this thing up there.  i completely re-wrote sorting for my ZC clients, as i could never get the base ZC to work as i would like.  i never created a plugin.
- just because they "fixed" it in base ZC 156, does not make it right.  if you look at that code, while it may work; it does not make sense to me.  the var $order_str ideally should just contain the order by statement.  nothing else.  if you are concatenating to it (with the `.=`), it should **NEVER** start with `order by`.  it should just be adding fields.  IMO.  follow that var in the base; while it does work, the logic is illogical.
- i have not implemented or tested your mod.  but i think it's looking for trouble, you create the var `$multi_sort` and assign it to `$order_str` on line 376.  then you rely on the if statement on line 433 to ideally coincide with your code above to indicate whether the order by is there or not.  if you concatenate that string, you could have 2 order by statements.

i hope that makes sense to you.  i agree that looking at sorting in ZC makes my head spin.  i'm hopeful that laravel will make it easier.  with laravel, i do not think we will not need to keep track of whether the `order by` is there or not.

**Comment by torvista** [comment]
All comments gratefully received, thanks for looking at the detail.
I had no time nor interest in revising this old code, it was only to help out the forum user, and took far longer to correct than I could justify.
Consequently I will look at this further when I am in the right frame of mind...

**Comment by torvista** [comment]
> i have not implemented or tested your mod. but i think it's looking for trouble, you create the var $multi_sort and assign it to $order_str on line 376. then you rely on the if statement on line 433 to ideally coincide with your code above to indicate whether the order by is there or not. if you concatenate that string, you could have 2 order by statements.

Finally noticed this was broken/never could have worked anyway!
